import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { formatDate, honestSentence, type StorageTerm } from './ttl.js'

/**
 * archive.json and PUBLISHED.md are TRACKED files: they are what Tsering hands
 * to the world. They hold only public identifiers — the feed owner ADDRESS
 * (never the key), the topic, and the feed manifest reference.
 *
 * Nothing here is ever read back to decide a feed index; the index always
 * comes from the network (see feed.ts → resolveNextIndex). `latestEdition`
 * is informational, for humans.
 */
export const ARCHIVE_SCHEMA = 'himalayan-archive/1'

export interface ArchiveRecord {
  schema: typeof ARCHIVE_SCHEMA
  title: string
  feed: {
    /** Feed owner: the public address of the archive's signer. */
    owner: string
    /** 32-byte topic, hex. */
    topic: string
    /** The text the topic was hashed from (keccak256). */
    topicString: string
    type: 'sequence'
  }
  /** THE address. It stays the same when the contents change. */
  address: {
    feedManifest: string
    bzzUrl: string
    cid: string
  }
  latestEdition: {
    collectionReference: string
    publishedAtIndex: string
    publishedAt: string
    fileCount: number
    bytes: number
  }
  storage: {
    batchId: string
    ttlSecondsAtPublish: number | null
    paidUntil: string | null
    asOf: string
    source: StorageTerm['source']
    note: string
  }
  recover: {
    cli: string
    curl: string
    reader: string
  }
}

export function archiveJsonPath(root: string): string {
  return path.join(root, 'archive.json')
}

export function writeArchiveJson(root: string, record: ArchiveRecord): string {
  const file = archiveJsonPath(root)
  writeFileSync(file, JSON.stringify(record, null, 2) + '\n', 'utf8')
  return file
}

/** Owner / topic / manifest only — the publisher's `status` screen uses these to know which feed to ask about. */
export interface PublishedIdentifiers {
  owner: string
  topic: string
  topicString: string
  feedManifest: string
  batchId: string
  title: string
}

export function readPublishedIdentifiers(root: string): PublishedIdentifiers | null {
  const file = archiveJsonPath(root)
  if (!existsSync(file)) return null
  const rec = JSON.parse(readFileSync(file, 'utf8')) as ArchiveRecord
  return {
    owner: rec.feed.owner,
    topic: rec.feed.topic,
    topicString: rec.feed.topicString,
    feedManifest: rec.address.feedManifest,
    batchId: rec.storage.batchId,
    title: rec.title,
  }
}

export function writePublishedMd(root: string, rec: ArchiveRecord, term: StorageTerm): string {
  const paid = term.paidUntil ? formatDate(term.paidUntil) : 'unknown'
  const md = `# ${rec.title}

> ${honestSentence(term)}

This file is generated by \`npm run archive -- publish\`. It is the whole
hand-over: anyone holding **one** of the addresses below can get every folio
back — without this repository, without the publishing app, and without
Tsering.

## The archive address (never changes)

\`\`\`
${rec.address.feedManifest}
\`\`\`

Open it in any Swarm gateway — a gallery with every folio, and a checksum for each:

\`\`\`
${rec.address.bzzUrl}
\`\`\`

CID form: \`${rec.address.cid}\`

## The feed behind it

If you prefer to go to the feed yourself (or rebuild everything from scratch):

| | |
|---|---|
| Feed owner (public address) | \`${rec.feed.owner}\` |
| Feed topic (hex) | \`${rec.feed.topic}\` |
| Feed topic (text, keccak256-hashed) | \`${rec.feed.topicString}\` |
| Feed type | sequence |

Owner:

\`\`\`
${rec.feed.owner}
\`\`\`

Topic:

\`\`\`
${rec.feed.topic}
\`\`\`

## Recover everything

\`\`\`bash
# 1. with this repo's CLI (reads only the identifiers you pass it)
${rec.recover.cli}

# 2. with nothing but curl
${rec.recover.curl}
\`\`\`

3. Or open \`${rec.recover.reader}\` (a single HTML file, no install) and paste the address, or the owner and topic.
   A copy travels inside every edition: ${rec.address.bzzUrl}recover.html

See \`docs/RECOVERY.md\` for the byte-level description, in case every tool in this repo is gone too.

## How long it is paid for

| | |
|---|---|
| Postage batch | \`${rec.storage.batchId}\` |
| Paid until (node estimate) | ${paid} |
| Estimate taken | ${formatDate(rec.storage.asOf)} |

${rec.storage.note}

## Latest edition (informational)

| | |
|---|---|
| Feed index | ${rec.latestEdition.publishedAtIndex} |
| Collection reference | \`${rec.latestEdition.collectionReference}\` |
| Files | ${rec.latestEdition.fileCount} |
| Published | ${rec.latestEdition.publishedAt} |

The collection reference is a snapshot of *this* edition. Hand out the archive address above instead: it always points at the newest edition.
`
  const file = path.join(root, 'PUBLISHED.md')
  writeFileSync(file, md, 'utf8')
  return file
}
