/**
 * Builds reader/recover.html: the template with swarm-lite.js inlined, so the
 * result is ONE self-contained file that works from file://, any static host,
 * or from inside the archive itself (/bzz/<address>/recover.html).
 *
 *   npm run build:reader
 */
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const lib = readFileSync(path.join(root, 'reader', 'swarm-lite.js'), 'utf8')
const template = readFileSync(path.join(root, 'reader', 'recover.template.html'), 'utf8')

const MARKER = '/*__SWARM_LITE__*/'
if (!template.includes(MARKER)) throw new Error(`Template is missing ${MARKER}`)

// Same code, minus the `export` keywords (it becomes part of one inline module).
const inlined = lib.replace(/^export (?=(async )?function |const )/gm, '')
if (/^export /m.test(inlined)) throw new Error('swarm-lite.js has an export form the inliner does not handle')

const banner = `<!-- GENERATED by scripts/build-reader.ts from recover.template.html + swarm-lite.js. Edit those, not this file. -->\n`
const body = template.replace(MARKER, () => `// ---- swarm-lite.js (inlined) ----\n${inlined}\n// ---- end swarm-lite.js ----`)
const html = body.replace(/^<!doctype html>\r?\n/i, (doctype) => doctype + banner)
writeFileSync(path.join(root, 'reader', 'recover.html'), html, 'utf8')
console.log(`reader/recover.html written (${(html.length / 1024).toFixed(1)} KB, zero dependencies)`)
